server:
  port: 8083

spring:
  application:
    name: service-a
  config:
    import: configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# actuator
management:
  endpoints:
    web:
      exposure:
        include: refresh
